graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Software System - Containers"]
    style diagram fill:#ffffff,stroke:#ffffff

    1["<div style='font-weight: bold'>User</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div>"]
    style 1 fill:#08427b,stroke:#052e56,color:#ffffff

    subgraph 2 [Software System]
      style 2 fill:#ffffff,stroke:#0b4884,color:#0b4884

      3("<div style='font-weight: bold'>Web Application</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div>")
      style 3 fill:#438dd5,stroke:#2e6295,color:#ffffff
      4("<div style='font-weight: bold'>Database</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div>")
      style 4 fill:#438dd5,stroke:#2e6295,color:#ffffff
    end

    1-. "<div>Uses</div><div style='font-size: 70%'></div>" .->3
    3-. "<div>Reads from and writes to</div><div style='font-size: 70%'></div>" .->4
  end