name: Structurizr DSL Workflow with Pre-built On-Premises Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull Structurizr On-Premises Image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: structurizr-onpremises:latest
          load: true  # Load the image into the runner's daemon

      - run: mkdir -p mermaid

      - run: |
          for dsl_file in $(find . -name "*.dsl"); do
            # ... (rest of your workflow steps)
            docker run --rm -v $GITHUB_WORKSPACE:/workspace structurizr-onpremises:latest export -i /workspace/${dsl_file} -o /workspace/${mermaid_file} --format mermaid
            # ...
          done
