name: Process DSL and Export to Mermaid

on:
  push:
    paths:
      - 'workspace-3.dsl'  # Path to the DSL file in the root directory

jobs:
  process-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: structurizr/cli:latest
            options: -v ${{ github.workspace }}:/var/www
            run: |
                sudo apt-get update
                sudo apt-get install -y docker.io
                docker run --rm -it -v $(pwd):/home local/structurizr:latest \
                export -workspace workspace-3.dsl -format mermaid -o ./
      - name: Commit exported Mermaid diagram
        uses: EndBug/add-and-commit@v8
        with:
          author_name: GitHub Action
          author_email: github-actions@github.com
          message: "[Automated] Added Mermaid diagram from DSL"
          add: architecture.mermaid

