name: Structurizr to Mermaid Conversion

on: [push]

jobs:
  convert-dsl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Pull Structurizr CLI image
        run: docker pull structurizr/cli:latest

      - name: Run Structurizr CLI
        run: |
          docker run --rm -v $(pwd):/usr/local/structurizr structurizr/cli:latest \
            export -workspace /usr/local/structurizr/*.dsl -format mermaid -output /usr/local/structurizr/mermaid

      - name: Commit Mermaid files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Converted DSL files to Mermaid"
          branch: main
          file_pattern: mermaid/*
