name: Generate Mermaid Diagrams from Structurizr DSL

on:
  push:
    branches: [main]
    paths:
      - '**/*.dsl'
  pull_request:
    paths:
      - '**/*.dsl'

jobs:
  update-diagrams:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-structurizr-image --cache-from my-structurizr-image:latest .

      - name: Process DSL Files
        run: docker run --rm -v ${{ github.workspace }}:/usr/local/structurizr my-structurizr-image
