name: Process DSLs and Export to Mermaid

on:
  push:
    paths:
      - '*.dsl'  # Trigger on any DSL file change in the root directory

jobs:
  process-and-export:
    runs-on: ubuntu-latest

    env:
      # Use Environment Files for DSL paths (recommended)
      DSL_FILE_PATH: ./DSL_FILES.env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load DSL file paths from Environment File (optional)
        id: load_dsl_files
        env:
          DSL_FILE_PATH: ./DSL_FILES.env  # Update path if your file is elsewhere
        run: |
          # Use file if it exists; otherwise, fallback to finding files directly
          if [ -f "$DSL_FILE_PATH" ]; then
            DSL_FILES=$(cat $DSL_FILE_PATH)
          else
            echo "::warning:: Environment file '$DSL_FILE_PATH' not found. Falling back to searching for .dsl files..."
            DSL_FILES=$(find . -name '*.dsl' -type f)
          fi

      - name: Set up DSL files for Structurizr CLI
        run: |
          mkdir -p $GITHUB_WORKSPACE/dsl
          # Use DSL_FILES from either Environment File or search if not available
          for file in $DSL_FILES; do
            cp $file $GITHUB_WORKSPACE/dsl/
          done

      - name: Export Structurizr workspaces
        uses: gilbertotcc/structurizr-action@v1
        with:
          args: export -workspace "$GITHUB_WORKSPACE/dsl" -format mermaid -output mermaid

      - name: Commit exported Mermaid diagrams
        uses: EndBug/add-and-commit@v8
        with:
          author_name: GitHub Action
          author_email: github-actions@github.com
          message: "[Automated] Added Mermaid diagrams from DSLs"
          add: .
          cwd: mermaid
          default_author: github_actor
          pathspec_error_handling: ignore
          push: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

