name: Process DSLs and Export to Mermaid

on:
  push:
    paths:
      - '*.dsl'  # Trigger on any DSL file change in the root directory

jobs:
  process-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find DSL files in root directory
        run: |
          DSL_FILES=$(find . -name '*.dsl' -type f)
          echo "::set-env name=DSL_FILES::$DSL_FILES"  # Set environment variable

      - name: Set up DSL files for Structurizr CLI
        run: |
          mkdir -p $GITHUB_WORKSPACE/dsl
          for file in $DSL_FILES; do  # Access variable directly
            cp $file $GITHUB_WORKSPACE/dsl/
          done

      - name: Export Structurizr workspaces
        uses: gilbertotcc/structurizr-action@v1
        with:
          args: export -workspace "$GITHUB_WORKSPACE/dsl" -format mermaid -output mermaid

      - name: Commit exported Mermaid diagrams
        uses: EndBug/add-and-commit@v8
        with:
          author_name: GitHub Action
          author_email: github-actions@github.com
          message: "[Automated] Added Mermaid diagrams from DSLs"
          add: .
          cwd: mermaid
          default_author: github_actor
          pathspec_error_handling: ignore
          push: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
