name: Generate Mermaid Diagrams from Structurizr DSL

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  update-diagrams:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Structurizr CLI
        run: |
          npm install -g structurizr-cli

      - name: Process DSL Files
        shell: bash
        run: |
          for dsl_file in $(find . -name "*.dsl"); do
            user_name=$(cut -d '/' -f 2 <<<"$dsl_file")
            base_name=$(basename "$dsl_file" .dsl)
            mermaid_file="mermaid/$user_name/$base_name.mermaid"

            if [[ -f "$mermaid_file" ]]; then
              echo "Updating existing Mermaid diagram: $mermaid_file"
              structurizr-cli export --force "$dsl_file" "$mermaid_file"
            else
              echo "Creating new Mermaid diagram: $mermaid_file"
              structurizr-cli export "$dsl_file" "$mermaid_file"
            fi
          done

      - name: Commit changes
        if: always()
        run: |
          git add mermaid/
          git commit -m "Updated Mermaid diagrams from DSL changes"

      - name: Push changes (optional)
        if: github.event_name == 'push'
        run: git push origin

