name: Structurizr DSL Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Adjust this based on your CLI compatibility
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: |
          echo "Downloading Structurizr CLI..."
          curl -o structurizr-cli.zip -L https://github.com/structurizr/cli/releases/download/v1.35.0/structurizr-cli-1.35.0.zip
          echo "Verifying download..."
          file $GITHUB_WORKSPACE/structurizr-cli.zip | grep Zip
          echo "Extracting JAR file..."
          unzip structurizr-cli.zip

      # Verify location and adjust if needed
      - run: |
          echo "Listing workspace contents:"
          ls -l $GITHUB_WORKSPACE
          # Check if structurizr-cli.jar is actually where you expect
          # Modify `*.jar` if the naming is different
          mv $(find . -name "structurizr-cli-*.jar" -type f) $GITHUB_WORKSPACE/structurizr-cli.jar
          echo "Verifying JAR file presence:"
          ls -l $GITHUB_WORKSPACE/structurizr-cli.jar | grep structurizr-cli.jar

      # Assuming your lib folder is at the root of your repository
      - run: |
          export CLASSPATH="$GITHUB_WORKSPACE/structurizr-cli.jar:$GITHUB_WORKSPACE/lib/*"

      - run: mkdir -p mermaid
      - run: |
          for dsl_file in $(find . -name "*.dsl"); do
            user_name=$(echo "${dsl_file}" | cut -d'/' -f2)
            base_name=$(basename "${dsl_file}" .dsl)
            mermaid_file="mermaid/${user_name}-${base_name}.mmd"
            echo "Processing DSL file: $dsl_file"
            echo "Generating Mermaid diagram: $mermaid_file"
            if [ -f "${mermaid_file}" ]; then
              java -cp "$CLASSPATH" com.structurizr.cli.CliApplication export -i "${dsl_file}" -o "${mermaid_file}" --format mermaid --force
            else
              java -cp "$CLASSPATH" com.structurizr.cli.CliApplication export -i "${dsl_file}" -o "${mermaid_file}" --format mermaid
            fi
            echo "Completed processing for $dsl_file"
          done
