name: Process DSL and Export to Mermaid

on:
  push:
    paths:
      - 'workspace-3.dsl'  # Replace with the actual path to your DSL file
      #  - '**/*.dsl'

jobs:
  process-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run structurizr-cli action
        uses: aidmax/structurizr-cli-action@v1
        with:
          version: latest  # Or specify a specific version if needed

      - name: Process DSL file
        run: structurizr process -f workspace-3.dsl

      - name: Export to Mermaid
        run: structurizr export -f mermaid -o architecture.mermaid

      - name: Commit exported Mermaid diagram
        uses: EndBug/add-and-commit@v8
        with:
          author_name: GitHub Action
          author_email: github-actions@github.com
          message: "[Automated] Added Mermaid diagram from DSL"
          add: architecture.mermaid
