name: Structurizr DSL Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Ensure compatibility with Structurizr CLI
          java-version: '17'      # Adjust if required
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: |
          curl -o structurizr-cli.zip -L https://github.com/structurizr/cli/releases/download/v1.35.0/structurizr-cli-1.35.0.zip
          unzip structurizr-cli.zip
          cp $(find . -name "structurizr-cli-*.jar" -type f) $GITHUB_WORKSPACE/structurizr-cli.jar
      - run: |
          if [[ ! -f $GITHUB_WORKSPACE/structurizr-cli.jar || -z $(file $GITHUB_WORKSPACE/structurizr-cli.jar | grep Zip) ]]; then
            echo "Structurizr CLI jar download incomplete or invalid."
            exit 1
          fi
      - run: |
          echo "Classpath: $CLASSPATH"
          echo "CLI jar path: $GITHUB_WORKSPACE/structurizr-cli.jar"
      - run: mkdir -p mermaid
      - run: |
          for dsl_file in $(find . -name "*.dsl"); do
            user_name=$(echo "${dsl_file}" | cut -d'/' -f2)
            base_name=$(basename "${dsl_file}" .dsl)
            mermaid_file="mermaid/${user_name}-${base_name}.mmd"

            if [ -f "${mermaid_file}" ]; then
              java -cp ".:${GITHUB_WORKSPACE}/structurizr-cli.jar" com.structurizr.cli.CliApplication export -i "${dsl_file}" -o "${mermaid_file}" --format mermaid --force
            else
              java -cp ".:${GITHUB_WORKSPACE}/structurizr-cli.jar" com.structurizr.cli.CliApplication export -i "${dsl_file}" -o "${mermaid_file}" --format mermaid
            fi
          done
