name: Generate Mermaid Diagrams from Structurizr DSL

on:
  push:
    branches: [main]
    paths:
      - '**/*.dsl'  # Trigger only when DSL files change
  pull_request:
    paths:
      - '**/*.dsl'  # Trigger on pull requests with DSL changes

jobs:
  update-diagrams:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image (using prebuilt image)
        run: docker pull structurizr/cli:latest

      - name: Process DSL Files
        run: docker run --rm -v $PWD:/usr/local/structurizr structurizr/cli /usr/local/structurizr/process_dsl.sh  # Change path to match prebuilt image's working directory

      - name: Commit changes
        if: always()
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git add mermaid/
          git commit -m "Updated Mermaid diagrams from DSL changes"

      - name: Push changes (optional)
        if: github.event_name == 'push'
        run: git push origin
