name: Generate Mermaid Diagrams from Structurizr DSL

on:
  push:
    branches: [main]
    paths:
      - '**/*.dsl'  # Trigger only when DSL files change
  pull_request:
    paths:
      - '**/*.dsl'  # Trigger on pull requests with DSL changes

jobs:
  update-diagrams:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-structurizr-image .  # Build image using Dockerfile with CMD

      - name: Process DSL Files
        run: docker run --rm -v $PWD:/usr/local/structurizr my-structurizr-image  # No need to specify a command
