name: Structurizr DSL Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - uses: ghcr.io/structurizr/cli-action@v1
      - run: mkdir -p mermaid
      - run: |
          for dsl_file in $(find . -name "*.dsl"); do
            user_name=$(echo "${dsl_file}" | cut -d'/' -f2)
            base_name=$(basename "${dsl_file}" .dsl)
            mermaid_file="mermaid/${user_name}-${base_name}.mmd"

            if [ -f "${mermaid_file}" ]; then
              java -cp ".:${GITHUB_WORKSPACE}/structurizr-cli-1.35.0.jar" com.structurizr.cli.CliApplication export -i "${dsl_file}" -o "${mermaid_file}" --format mermaid --force
            else
              java -cp ".:${GITHUB_WORKSPACE}/structurizr-cli-1.35.0.jar" com.structurizr.cli.CliApplication export -i "${dsl_file}" -o "${mermaid_file}" --format mermaid
            fi
          done
