name: Structurizr to Mermaid Conversion

on: [push]  # Trigger the workflow on push events

jobs:
  convert-dsl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (optional)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          context: .  # Assuming Dockerfile is in the root
          file: Dockerfile  # Replace with your Dockerfile name if needed
          push: false
          tags: structurizr-cli  # Replace with your desired tag

      - name: Run Structurizr CLI
        run: |
          docker run --rm -v $(pwd):/workspace structurizr-cli:latest \
            workspace-convert /workspace/*.dsl /workspace/mermaid/*.mmd \
            --format mermaid

      - name: Commit Mermaid files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Converted DSL files to Mermaid"
          branch: main
          file_pattern: mermaid/*
