name: Generate Mermaid Diagrams from Structurizr DSL

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  update-diagrams:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker://structurizr/cli:latest
        with:
          args: export -i /usr/local/structurizr/**/*.dsl -o /usr/local/structurizr/mermaid/ --format mermaid

      - name: Commit changes
        if: always()
        run: |
          git add mermaid/
          git commit -m "Updated Mermaid diagrams from DSL changes"
      - name: Push changes (optional)
        if: github.event_name == 'push'
        run: git push origin
