name: Structurizr DSL Workflow

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Install Structurizr CLI
      run: |
        curl -o structurizr-cli.zip -L https://github.com/structurizr/cli/releases/download/v1.35.0/structurizr-cli-1.35.0.zip
        unzip structurizr-cli.zip
        chmod +x lib/structurizr-cli-1.35.0.jar
        sudo mv lib/structurizr-cli-1.35.0.jar /usr/local/bin/structurizr-cli
    # - name: Download and Install Structurizr CLI
    #   run: |
    #     curl -o structurizr-cli.zip -L https://github.com/structurizr/cli/releases/download/v1.35.0/structurizr-cli-1.35.0.zip
    #     unzip structurizr-cli.zip
    #     chmod +x structurizr-cli-1.35.0/lib/structurizr-cli-1.35.0.jar
    #     sudo mv structurizr-cli-1.35.0/lib/structurizr-cli-1.35.0.jar /usr/local/bin/structurizr-cli
    # - name: Download and Install Structurizr CLI
    #   run: |
    #     curl -o structurizr-cli.zip -L https://github.com/structurizr/cli/releases/download/v1.35.0/structurizr-cli-1.35.0.zip
    #     unzip structurizr-cli.zip
    #     chmod +x structurizr-cli-1.35.0/lib/structurizr-cli-1.35.0.jar
    #     sudo mv structurizr-cli-1.35.0/lib/*.jar /usr/local/bin/structurizr-cli

    - name: Create Mermaid Directory
      run: mkdir -p mermaid

    # - name: Process DSL Files
    #   run: |
    #     for dsl_file in $(find . -name "*.dsl"); do
    #       # Extract user name from the file path (customize this based on your directory structure)
    #       user_name=$(echo "${dsl_file}" | cut -d'/' -f2)
  
    #       # Extract base name from the DSL file (without extension)
    #       base_name=$(basename "${dsl_file}" .dsl)
  
    #       mermaid_file="mermaid/${user_name}-${base_name}.mmd"
  
    #       # Check if the Mermaid file already exists
    #       if [ -f "${mermaid_file}" ]; then
    #         # If it exists, update it
    #         java -jar /usr/local/bin/structurizr-cli export -i "${dsl_file}" -o "${mermaid_file}" --format mermaid --force
    #       else
    #         # If it doesn't exist, create it
    #         java -jar /usr/local/bin/structurizr-cli export -i "${dsl_file}" -o "${mermaid_file}" --format mermaid
    #       fi
    #     done
    # - name: Process DSL Files
    #   run: |
    #     for dsl_file in $(find . -name "*.dsl"); do
    #       # Extract user name from the file path (customize this based on your directory structure)
    #       user_name=$(echo "${dsl_file}" | cut -d'/' -f2)
      
    #       # Extract base name from the DSL file (without extension)
    #       base_name=$(basename "${dsl_file}" .dsl)
      
    #       mermaid_file="mermaid/${user_name}-${base_name}.mmd"
      
    #       # Check if the Mermaid file already exists
    #       if [ -f "${mermaid_file}" ]; then
    #         # If it exists, update it
    #         java -jar structurizr-cli-1.35.0/lib/structurizr-cli-1.35.0.jar export -i "${dsl_file}" -o "${mermaid_file}" --format mermaid --force
    #       else
    #         # If it doesn't exist, create it
    #         java -jar structurizr-cli-1.35.0/lib/structurizr-cli-1.35.0.jar export -i "${dsl_file}" -o "${mermaid_file}" --format mermaid
    #       fi
    #     done
    - name: Process DSL Files
      run: |
        for dsl_file in $(find . -name "*.dsl"); do
          # Extract user name from the file path (customize this based on your directory structure)
          user_name=$(echo "${dsl_file}" | cut -d'/' -f2)
      
          # Extract base name from the DSL file (without extension)
          base_name=$(basename "${dsl_file}" .dsl)
      
          mermaid_file="mermaid/${user_name}-${base_name}.mmd"
      
          # Check if the Mermaid file already exists
          if [ -f "${mermaid_file}" ]; then
            # If it exists, update it
            java -jar ./structurizr-cli-1.35.0/lib/structurizr-cli-1.35.0.jar export -i "${dsl_file}" -o "${mermaid_file}" --format mermaid --force
          else
            # If it doesn't exist, create it
            java -jar ./structurizr-cli-1.35.0/lib/structurizr-cli-1.35.0.jar export -i "${dsl_file}" -o "${mermaid_file}" --format mermaid
          fi
        done
