name: Process DSLs and Export to Mermaid

on:
  push:
    paths:
      - '*.dsl'  # Trigger on any DSL file change in the root directory

jobs:
  process-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find DSL files
        id: find_dsl_files
        run: |
          echo "::set-output name=dsl_files::$(find . -name '*.dsl' -type f)"

      - name: Export Structurizr workspaces
        uses: gilbertotcc/structurizr-action@v1
        with:
          args: ${{ format('export -workspace {0} -format mermaid -output mermaid', steps.find_dsl_files.outputs.dsl_files) }}

      - name: Commit exported Mermaid diagrams
        uses: EndBug/add-and-commit@v8
        with:
          author_name: GitHub Action
          author_email: github-actions@github.com
          message: "[Automated] Added Mermaid diagrams from DSLs"
          add: '**/*.mmd'  # Updated pathspec to include all Mermaid files
          cwd: mermaid  # Set the working directory to mermaid
          default_author: github_actor
          pathspec_error_handling: ignore
          push: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

# Address deprecated `set-output` warnings:
# 1. Replace outdated syntax with environment variables in `structurizr-action` step.
# 2. Update other steps accordingly or switch to using built-in `git` action for commit/push.

