name: Structurizr to Mermaid Conversion

on: [push]

jobs:
  convert-dsl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Pull Structurizr CLI image
        run: docker pull structurizr/cli:latest

      - name: Run Structurizr CLI
        run: docker run --rm -v $(pwd):/workspace structurizr/cli:latest \
          export --workspace /workspace/workspace.dsl --format mermaid

      - name: Upload Mermaid files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mermaid-diagrams
          path: mermaid/*.mmd
