name: Structurizr DSL Workflow with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Pull Structurizr Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .  # Use current directory as context
          push: false  # No need to push an image
          tags: structurizr  # Tag the image for easy reference
          load: true  # Load the image into the runner's Docker daemon
      - run: mkdir -p mermaid
      - run: |
          for dsl_file in $(find . -name "*.dsl"); do
            user_name=$(echo "${dsl_file}" | cut -d'/' -f2)
            base_name=$(basename "${dsl_file}" .dsl)
            mermaid_file="mermaid/${user_name}-${base_name}.mmd"
            echo "Processing DSL file: $dsl_file"
            echo "Generating Mermaid diagram: $mermaid_file"
            docker run --rm -v $GITHUB_WORKSPACE:/workspace structurizr export -i /workspace/${dsl_file} -o /workspace/${mermaid_file} --format mermaid
            echo "Completed processing for $dsl_file"
          done
