name: Structurizr DSL Workflow

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"

    - name: Install Structurizr CLI
      run: brew install structurizr-cli

    - name: Create Mermaid Directory
      run: mkdir -p mermaid

    - name: Process DSL Files
      run: |
        for dsl_file in $(find . -name "*.dsl"); do
          # Extract user name from the file path (customize this based on your directory structure)
          user_name=$(echo "${dsl_file}" | cut -d'/' -f2)

          # Extract base name from the DSL file (without extension)
          base_name=$(basename "${dsl_file}" .dsl)

          mermaid_file="mermaid/${user_name}-${base_name}.mmd"

          # Check if the Mermaid file already exists
          if [ -f "${mermaid_file}" ]; then
            # If it exists, update it
            structurizr-cli export -i "${dsl_file}" -o "${mermaid_file}" --format mermaid --force
          else
            # If it doesn't exist, create it
            structurizr-cli export -i "${dsl_file}" -o "${mermaid_file}" --format mermaid
          fi
        done
