name: Process DSLs and Export to Mermaid

on:
  push:
    paths:
      - '*.dsl'  # Trigger on any DSL file change in the root directory

jobs:
  process-and-export:
    runs-on: ubuntu-latest

    env:
      DSL_FILES: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find DSL files
        id: find_dsl_files
        run: |
          export DSL_FILES=$(find . -name '*.dsl' -type f)

      - name: Export Structurizr workspaces
        uses: gilbertotcc/structurizr-action@v1
        with:
          args: export -workspace "${DSL_FILES}" -format mermaid -output mermaid

      - name: Commit exported Mermaid diagrams
        uses: EndBug/add-and-commit@v8
        with:
          author_name: GitHub Action
          author_email: github-actions@github.com
          message: "[Automated] Added Mermaid diagrams from DSLs"
          add: .
          cwd: mermaid
          default_author: github_actor
          pathspec_error_handling: ignore
          push: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
