name: Generate Mermaid Diagrams from Structurizr DSL

on:
  push:
    branches: [main]
  pull_request:

jobs:
  update-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Homebrew
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> $HOME/.profile
          eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

      - name: Install structurizr-cli
        run: brew install structurizr-cli

      - name: Process DSL Files
        run: |
          find . -name "*.dsl" -exec structurizr-cli export -i {} -o /workspace/mermaid/ --format mermaid \;

      - name: Commit changes
        if: always()
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git add mermaid/
          git commit -m "Updated Mermaid diagrams from DSL changes"
          
      - name: Push changes (optional)
        if: github.event_name == 'push'
        run: git push origin
