name: Process DSLs and Export to Mermaid

on:
  push:
    paths:
      - '*.dsl'  # Trigger on any DSL file change in the root directory

jobs:
  process-and-export:
    runs-on: ubuntu-latest

    env:
      # Use an empty DSL_FILES variable initially
      DSL_FILES: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load DSL file paths from Environment File
        id: load_dsl_files
        env:
          # Define location of the Environment File
          DSL_FILE_PATH: ./DSL_FILES.env
        run: |
          # Read each line of the file into the DSL_FILES variable
          DSL_FILES=$(cat $DSL_FILE_PATH)

      - name: Set up DSL files for Structurizr CLI
        run: |
          mkdir -p $GITHUB_WORKSPACE/dsl
          # Loop through each file path in DSL_FILES and copy them
          for file in $DSL_FILES; do
            cp $file $GITHUB_WORKSPACE/dsl/
          done

      - name: Export Structurizr workspaces
        uses: gilbertotcc/structurizr-action@v1
        with:
          args: export -workspace "$GITHUB_WORKSPACE/dsl" -format mermaid -output mermaid

      - name: Commit exported Mermaid diagrams
        uses: EndBug/add-and-commit@v8
        with:
          author_name: GitHub Action
          author_email: github-actions@github.com
          message: "[Automated] Added Mermaid diagrams from DSLs"
          add: .
          cwd: mermaid
          default_author: github_actor
          pathspec_error_handling: ignore
          push: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

