name: Generate Mermaid Diagrams from Structurizr DSL

on:
  push:
    branches: [main]
  pull_request:

jobs:
  update-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker pull alpine:latest  # Using alpine:latest for a minimal base image

      - name: Install Dependencies
        run: |
          docker run --rm -v $PWD:/workspace alpine:latest chmod +x process_dsl.sh  # No need for explicit chmod installation

      - name: Process DSL Files
        run: docker run --rm -v $PWD:/workspace alpine:latest /workspace/process_dsl.sh

      - name: Commit changes
        if: always()
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git add mermaid/
          git commit -m "Updated Mermaid diagrams from DSL changes"

      - name: Push changes (optional)
        if: github.event_name == 'push'
        run: git push origin
